variable "server-ami-id" {}
variable "instance-type" {}
variable "key-pair-name" {}
variable "ec2-security-group" {}
variable "ec2-subnet-id" {}
variable "environment" {}
variable "application" {}
variable "product" {}
variable "ansible-private-key-name" {}
variable "ansible-private-ip-address" {}
variable "nodejs-private-key-name" {}