---

- hosts: node-servers
  gather_facts: true
  remote_user: ubuntu
  become: yes
  tasks:
  - name: "update instance"
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: "Installing Node"
    shell:
      "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt-get install -y nodejs"
  - name: "Creating Directory"
    file:
      path: /etc/chatbot
      state: directory
      owner: ubuntu
  - name: "Downloading git repository"
    git:
      repo: https://github.com/abkunal/Chat-App-using-Socket.io
      dest: /etc/chatbot
  - name: "Moving to repository and installing dependecies"
    shell:
      "cd /etc/chatbot && npm install"
  - name: "Installing PM2 for managing node-servers"
    npm:
      name: pm2
      global: yes
  - name: "Starting ChatBot Server"
    shell:
      "pm2 start /etc/chatbot/app.js"
  - name: "Run ChatBot server on reboot"
    shell:
      "pm2 startup && sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu && pm2 save"